## Data restructuring for countries: UK, Indonesia, Singapore

This notebook documents the subsetting of the selected countries for the relevant datasets. Saved datasets to be used for modelling later.

Location key (for whole country) = GB, ID, SG

Datasets used:
- epidemiology.csv
- vaccinations.csv
- mobility.csv
- google-search-trends.csv
- vaccination-search-insights.csv
- government-response.csv
- index.csv

## Part 1: Data restructuring

In [1]:
import pandas as pd
import dask.dataframe as dd

In [2]:
FILE_PATH = r"../datasets/"
selected_countries = ["GB", "ID", "SG"]

### Selecting the countries from the epidemiology dataset

In [3]:
df_epidemiology = dd.read_csv(FILE_PATH+"epidemiology.csv", dtype={'cumulative_confirmed': 'float64', 'cumulative_deceased': 'float64', 'new_confirmed': 'float64', 'new_deceased': 'float64'})

df_index = pd.read_csv(FILE_PATH+"index.csv")

In [4]:
df_epidemiology.head()

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested
0,2020-01-01,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
1,2020-01-02,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
2,2020-01-03,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
3,2020-01-04,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
4,2020-01-05,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN

In [ ]:
len(df_epidemiology)

In [19]:
# Subset for the three countries
df_epidemiology_subset = df_epidemiology.loc[df_epidemiology["location_key"].isin(selected_countries)]

In [20]:
df_epidemiology_subset = df_epidemiology_subset.compute()

df_epidemiology_subset.head()

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested
982706,2020-01-01,GB,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
982707,2020-01-02,GB,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
982708,2020-01-03,GB,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
982709,2020-01-04,GB,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
982710,2020-01-05,GB,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN

In [21]:
df_epidemiology_subset.to_csv(r"../generated_data/cp3_modelling/epidemiology_subset.csv")

### Selecting the countries from the vaccinations dataset

In [22]:
df_vaccinations = dd.read_csv(FILE_PATH+"vaccinations.csv", dtype={'cumulative_vaccine_doses_administered': 'float64'})

In [23]:
df_vaccinations.head(5)

,date,location_key,new_persons_vaccinated,cumulative_persons_vaccinated,new_persons_fully_vaccinated,cumulative_persons_fully_vaccinated,new_vaccine_doses_administered,cumulative_vaccine_doses_administered,new_persons_vaccinated_pfizer,cumulative_persons_vaccinated_pfizer,...,new_persons_fully_vaccinated_janssen,cumulative_persons_fully_vaccinated_janssen,new_vaccine_doses_administered_janssen,cumulative_vaccine_doses_administered_janssen,new_persons_vaccinated_sinovac,total_persons_vaccinated_sinovac,new_persons_fully_vaccinated_sinovac,total_persons_fully_vaccinated_sinovac,new_vaccine_doses_administered_sinovac,total_vaccine_doses_administered_sinovac
0,2021-01-25,AD,NaN,576.0,NaN,NaN,NaN,576.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-02-01,AD,460.0,1036.0,NaN,NaN,460.0,1036.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-02-10,AD,255.0,1291.0,NaN,NaN,255.0,1291.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-02-12,AD,331.0,1622.0,NaN,NaN,331.0,1622.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-02-19,AD,519.0,2141.0,NaN,NaN,519.0,2141.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df_vaccinations_subset = df_vaccinations.loc[df_vaccinations["location_key"].isin(selected_countries)].compute()

df_vaccinations_subset.head()

,date,location_key,new_persons_vaccinated,cumulative_persons_vaccinated,new_persons_fully_vaccinated,cumulative_persons_fully_vaccinated,new_vaccine_doses_administered,cumulative_vaccine_doses_administered,new_persons_vaccinated_pfizer,cumulative_persons_vaccinated_pfizer,...,new_persons_fully_vaccinated_janssen,cumulative_persons_fully_vaccinated_janssen,new_vaccine_doses_administered_janssen,cumulative_vaccine_doses_administered_janssen,new_persons_vaccinated_sinovac,total_persons_vaccinated_sinovac,new_persons_fully_vaccinated_sinovac,total_persons_fully_vaccinated_sinovac,new_vaccine_doses_administered_sinovac,total_vaccine_doses_administered_sinovac
402023,2021-01-10,GB,NaN,2286572.0,NaN,391399.0,NaN,2677971.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
402024,2021-01-11,GB,145076.0,2431648.0,20768.0,412167.0,165844.0,2843815.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
402025,2021-01-12,GB,207661.0,2639309.0,16065.0,428232.0,223726.0,3067541.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
402026,2021-01-13,GB,278943.0,2918252.0,9745.0,437977.0,288688.0,3356229.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
402027,2021-01-14,GB,316694.0,3234946.0,5257.0,443234.0,321951.0,3678180.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df_vaccinations_subset.to_csv(r"../generated_data/cp3_modelling/vaccinations_subset.csv")

### Selecting the countries from the mobility dataset

In [36]:
df_mobility = dd.read_csv(FILE_PATH+"mobility.csv", dtype={'mobility_grocery_and_pharmacy': 'float64', 'mobility_parks': 'float64','mobility_residential': 'float64', 'mobility_retail_and_recreation': 'float64', 'mobility_transit_stations': 'float64', 'mobility_workplaces': 'float64'})

df_mobility.head(10)

,date,location_key,mobility_retail_and_recreation,mobility_grocery_and_pharmacy,mobility_parks,mobility_transit_stations,mobility_workplaces,mobility_residential
0,2020-02-15,AE,0.0,4.0,5.0,0.0,2.0,1.0
1,2020-02-16,AE,1.0,4.0,4.0,1.0,2.0,1.0
2,2020-02-17,AE,-1.0,1.0,5.0,1.0,2.0,1.0
3,2020-02-18,AE,-2.0,1.0,5.0,0.0,2.0,1.0
4,2020-02-19,AE,-2.0,0.0,4.0,-1.0,2.0,1.0
5,2020-02-20,AE,-2.0,1.0,6.0,1.0,1.0,1.0
6,2020-02-21,AE,-3.0,2.0,6.0,0.0,-1.0,1.0
7,2020-02-22,AE,-2.0,2.0,4.0,-2.0,3.0,1.0
8,2020-02-23,AE,-1.0,3.0,3.0,-1.0,4.0,1.0
9,2020-02-24,AE,-3.0,0.0,5.0,-1.0,3.0,1.0

In [37]:
df_mobility_subset = df_mobility.loc[df_mobility["location_key"].isin(selected_countries)].compute()

df_mobility_subset.head()

,date,location_key,mobility_retail_and_recreation,mobility_grocery_and_pharmacy,mobility_parks,mobility_transit_stations,mobility_workplaces,mobility_residential
379076,2020-02-15,GB,-12.0,-7.0,-35.0,-12.0,-4.0,2.0
379077,2020-02-16,GB,-7.0,-6.0,-28.0,-7.0,-3.0,1.0
379078,2020-02-17,GB,10.0,1.0,24.0,-2.0,-14.0,2.0
379079,2020-02-18,GB,7.0,-1.0,20.0,-3.0,-14.0,2.0
379080,2020-02-19,GB,6.0,-2.0,8.0,-4.0,-14.0,3.0

In [38]:
df_mobility_subset.to_csv(r"../generated_data/cp3_modelling/mobility_subset.csv")

### Selecting the countries from the search trends dataset

In [39]:
df_google_search = dd.read_csv(FILE_PATH+"google-search-trends.csv")

df_google_search.head(10)

,date,location_key,search_trends_abdominal_obesity,search_trends_abdominal_pain,search_trends_acne,search_trends_actinic_keratosis,search_trends_acute_bronchitis,search_trends_adrenal_crisis,search_trends_ageusia,search_trends_alcoholism,...,search_trends_visual_acuity,search_trends_vomiting,search_trends_wart,search_trends_water_retention,search_trends_weakness,search_trends_weight_gain,search_trends_wheeze,search_trends_xeroderma,search_trends_xerostomia,search_trends_yawn
0,2020-01-01,AU,3.56,5.38,10.76,0.52,0.35,0.12,0.05,5.36,...,0.70,4.23,1.87,0.39,0.47,4.47,0.30,3.52,0.43,0.21
1,2020-01-02,AU,3.46,5.35,11.30,0.55,0.36,0.14,0.06,4.62,...,0.44,3.97,1.97,0.41,0.47,4.60,0.27,3.48,0.45,0.19
2,2020-01-03,AU,3.40,5.35,11.23,0.53,0.34,0.12,0.05,4.63,...,0.29,3.90,1.85,0.40,0.65,4.46,0.30,3.58,0.39,0.18
3,2020-01-04,AU,3.43,5.23,10.68,0.42,0.35,0.11,0.05,4.82,...,0.28,3.88,1.78,0.38,0.54,4.43,0.30,3.59,0.40,0.21
4,2020-01-05,AU,3.29,5.14,10.20,0.49,0.38,0.11,NaN,4.26,...,0.38,3.73,1.75,0.34,0.46,4.59,0.34,3.09,0.40,0.19
5,2020-01-06,AU,3.52,5.23,10.83,0.49,0.36,0.14,0.05,4.07,...,0.36,3.64,1.88,0.36,0.53,4.86,0.34,3.15,0.44,0.21
6,2020-01-07,AU,3.62,5.21,11.17,0.55,0.41,0.13,0.06,4.05,...,0.37,3.64,1.92,0.40,0.48,4.95,0.31,3.20,0.45,0.21
7,2020-01-08,AU,3.54,5.17,11.39,0.54,0.36,0.13,0.05,3.98,...,0.33,3.59,1.88,0.40,0.50,4.96,0.26,3.23,0.44,0.20
8,2020-01-09,AU,3.40,5.11,11.09,0.52,0.33,0.14,0.05,4.36,...,0.32,3.46,1.97,0.43,0.50,4.78,0.27,3.08,0.44,0.21
9,2020-01-10,AU,3.26,5.22,11.13,0.48,0.35,0.15,0.04,4.80,...,0.25,3.61,1.86,0.38,0.45,4.49,0.26,3.24,0.46,0.23

In [40]:
df_google_search_subset = df_google_search.loc[df_google_search["location_key"].isin(selected_countries)].compute()

df_google_search_subset.head()

,date,location_key,search_trends_abdominal_obesity,search_trends_abdominal_pain,search_trends_acne,search_trends_actinic_keratosis,search_trends_acute_bronchitis,search_trends_adrenal_crisis,search_trends_ageusia,search_trends_alcoholism,...,search_trends_visual_acuity,search_trends_vomiting,search_trends_wart,search_trends_water_retention,search_trends_weakness,search_trends_weight_gain,search_trends_wheeze,search_trends_xeroderma,search_trends_xerostomia,search_trends_yawn
8874,2020-01-01,GB,3.10,5.81,8.52,0.24,0.70,0.07,0.06,6.97,...,0.55,4.85,1.38,0.22,0.38,3.28,0.52,3.15,0.45,0.16
8875,2020-01-02,GB,3.24,6.29,8.60,0.37,0.59,0.12,0.06,5.35,...,0.39,4.30,1.58,0.27,0.49,3.79,0.49,3.33,0.51,0.19
8876,2020-01-03,GB,2.85,6.08,8.72,0.29,0.69,0.09,0.06,4.82,...,0.31,3.96,1.56,0.28,0.49,3.72,0.47,3.22,0.38,0.17
8877,2020-01-04,GB,2.97,5.80,9.09,0.29,0.58,0.05,0.06,5.00,...,0.32,3.86,1.58,0.28,0.48,3.68,0.55,3.44,0.51,0.17
8878,2020-01-05,GB,3.84,5.82,9.16,0.36,0.62,0.07,0.08,4.54,...,0.34,4.09,1.67,0.26,0.57,4.14,0.47,3.31,0.46,0.22

In [41]:
# Restrict to covid related symptoms
ls_covid_symptoms = ['search_trends_fever', 'search_trends_low_grade_fever', 'search_trends_chills', 'search_trends_cough', 'search_trends_shallow_breathing', 'search_trends_shortness_of_breath', 'search_trends_fatigue', 'search_trends_muscle_weakness', 'search_trends_cluster_headache', 'search_trends_headache', 'search_trends_sore_throat', 'search_trends_nasal_congestion', 'search_trends_nausea', 'search_trends_vomiting', 'search_trends_diarrhea']

In [42]:
df_google_search_subset = df_google_search_subset[ls_covid_symptoms+["date", "location_key"]]
df_google_search_subset.head()

,search_trends_fever,search_trends_low_grade_fever,search_trends_chills,search_trends_cough,search_trends_shallow_breathing,search_trends_shortness_of_breath,search_trends_fatigue,search_trends_muscle_weakness,search_trends_cluster_headache,search_trends_headache,search_trends_sore_throat,search_trends_nasal_congestion,search_trends_nausea,search_trends_vomiting,search_trends_diarrhea,date,location_key
8874,4.07,0.11,0.32,9.27,0.05,1.03,6.26,0.16,0.22,5.37,3.28,2.48,2.37,4.85,5.24,2020-01-01,GB
8875,3.94,0.06,0.31,10.01,0.05,1.12,6.96,0.18,0.28,4.86,3.57,2.35,2.26,4.30,5.41,2020-01-02,GB
8876,3.80,0.06,0.31,9.77,0.09,1.02,6.77,0.18,0.24,4.59,3.32,2.50,2.22,3.96,5.16,2020-01-03,GB
8877,3.93,0.07,0.27,9.63,0.07,1.06,6.60,0.21,0.29,4.94,3.17,2.41,2.27,3.86,4.99,2020-01-04,GB
8878,3.90,0.06,0.25,9.64,0.10,1.15,7.69,0.20,0.23,5.16,3.39,2.27,2.40,4.09,5.16,2020-01-05,GB

In [43]:
df_google_search_subset.to_csv(r"../generated_data/cp3_modelling/google-search-trends_subset.csv")

### Selecting the countries from the vaccination search insights dataset

In [28]:
df_vacc_search = pd.read_csv(FILE_PATH+"vaccination-search-insights.csv")

df_vacc_search.head(10)

,date,key,sni_covid19_vaccination,sni_vaccination_intent,sni_safety_side_effects
0,2021-01-04,CA,33.963,4.520,5.881
1,2021-01-04,CA_AB,31.736,3.774,5.825
2,2021-01-04,CA_BC,35.991,4.243,6.136
3,2021-01-04,CA_MB,35.921,6.236,6.335
4,2021-01-04,CA_NB,27.852,2.853,4.950
5,2021-01-04,CA_NL,19.234,1.800,4.246
6,2021-01-04,CA_NS,24.736,2.965,4.328
7,2021-01-04,CA_NT,51.398,6.363,10.945
8,2021-01-04,CA_NU,50.693,5.722,10.641
9,2021-01-04,CA_ON,39.382,5.623,7.487

In [29]:
df_vacc_search_subset = df_vacc_search.loc[df_vacc_search["key"].isin(selected_countries)]

df_vacc_search_subset.head()

,date,key,sni_covid19_vaccination,sni_vaccination_intent,sni_safety_side_effects
14,2021-01-04,GB,67.078,8.562,8.871
3146,2021-01-11,GB,60.296,9.536,8.327
6271,2021-01-18,GB,54.432,8.003,7.847
9392,2021-01-25,GB,60.479,7.677,7.040
12512,2021-02-01,GB,58.335,6.495,7.443

In [31]:
df_vacc_search_subset.to_csv(r"../generated_data/cp3_modelling/vaccination_search_subset.csv")

## Reduced feature set and selected for countries for government dataset

In [32]:
# After lasso regression done by Khizer
reduced_featureset = ["school_closing", "workplace_closing", "cancel_public_events", "restrictions_on_gatherings", "public_transport_closing", "stay_at_home_requirements", "restrictions_on_internal_movement", "international_travel_controls", "income_support", "public_information_campaigns", "facial_coverings", "vaccination_policy"]

In [33]:
df_gvt_resp = pd.read_csv(FILE_PATH+"government-response.csv")

df_gvt_resp.head()

,date,location_key,school_closing,workplace_closing,cancel_public_events,restrictions_on_gatherings,public_transport_closing,stay_at_home_requirements,restrictions_on_internal_movement,international_travel_controls,...,fiscal_measures,international_support,public_information_campaigns,testing_policy,contact_tracing,emergency_investment_in_healthcare,investment_in_vaccines,facial_coverings,vaccination_policy,stringency_index
0,2020-01-01,AD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-01-02,AD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2020-01-03,AD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2020-01-04,AD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2020-01-05,AD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
df_gvt_resp_subset = df_gvt_resp.loc[df_gvt_resp["location_key"].isin(selected_countries)]

df_gvt_resp_subset = df_gvt_resp_subset[reduced_featureset + ["date", "location_key", "stringency_index"]]

df_gvt_resp_subset.head()

,school_closing,workplace_closing,cancel_public_events,restrictions_on_gatherings,public_transport_closing,stay_at_home_requirements,restrictions_on_internal_movement,international_travel_controls,income_support,public_information_campaigns,facial_coverings,vaccination_policy,date,location_key,stringency_index
120759,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-01,GB,0.0
120760,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-02,GB,0.0
120761,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-03,GB,0.0
120762,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-04,GB,0.0
120763,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-05,GB,0.0

In [35]:
df_gvt_resp_subset.to_csv(r"../generated_data/cp3_modelling/government_response_subset.csv")